### ISSUE TITLE
Adding a Sensor that measures more than one Quantity Kind

### ISSUE THREAD

**Issue by Baalmart** [Waziup/WaziCloud#231]
- What were you trying to achieve?
Trying to add a sensor that measure many quantity kinds. More like a purchased `Sensor` that has the same attributes as a `Device`.
- What are the expected results?
Ability to easily add a sensor which measures many quantity kinds
- What are the received results?
I can only be able to add one quantity kinds per sensor
- What are the steps to reproduce the issue?
Just visit the Dashboard, head to a device and then try to add a sensor
- In what environment did you encounter the issue?
Wazicloud dashboard.

**Comment by cdupont** [comment]
It's a good point...
Currently, we have a "Device" (e.g a WaziDev) that can contain several "Sensors". 
A sensor measures only one physical quantity, e.g. temperature, humidity...
However, it is possible that the thing measured has several values: e.g. a GPS position has 3 values: latitude, longitude, altitude.
In this case, it is stored in the sensor value as a JSON compound: `{latitude: 41.03265, longitude: 3.25698, altitude: 12}`.

Here is an example for sending GPS coordinates with WaziDev:
```
#include <WaziDev.h>

// new WaziDev with node address = 8 
WaziDev wazidev("MyDevice", 8);

void setup()
{
  wazidev.setup();

  // Open serial communications and wait for port to open:
  Serial.begin(38400);
  // Print a start message
  Serial.println(F("Tests of WaziDev communications"));
}

void loop(void)
{
  // Send GPS coordinates
  wazidev.send("\\!UID/MyDevice2/GPS/{\"BC\":2230,\"LAT\":-1.34683,\"LGT\":36.70799,\"FXT\":6,\"P\":\"N\"}");

  delay(3000);
}
```

**Comment by cdupont** [comment]
Anyway, if you have a commercial sensor that measures two different things (like the DHT11), I think it's preferable to create 2 sensors on the dashboard...

**Comment by Baalmart** [comment]
Okay, using JSON is a good approach. 
Thanks.
