### ISSUE TITLE
Not all devices are listed in wazicloud dashboard devices section

### ISSUE THREAD

**Issue by SvenZeisberg** [Waziup/WaziCloud#238]
A certain device is missing in the display of the devices dashboard in wazicloud (HTW-Lab-WaziDev-93-KB-KIT) ... (see picture)
![wazicloud_devices_missing](https://user-images.githubusercontent.com/62630067/108227454-340b5100-713e-11eb-801f-2d45c500aff5.gif)
...while in the project list of devices it appears as it should be (HTW-Lab-WaziDev-93-KB-KIT) ...(see picture 2):
![wazicloud_devices_missing_part2](https://user-images.githubusercontent.com/62630067/108227892-a1b77d00-713e-11eb-9df1-cacb932c3739.gif)

**Comment by cdupont** [comment]
From your second screenshot, I see the owner of HTW-Lab-WaziDev-93-KB-KIT is "guest".
So it doesn't appear in your "Devices" list, with your current filters.
You could find it by changing your filters and selecting "Show public resources" in your settings.

**Comment by cdupont** [comment]
Closing
