### ISSUE TITLE
WaziCloud error 500 fetching devices permissions in display for no good reason

### ISSUE THREAD

**Issue by SvenZeisberg** [Waziup/WaziCloud#240]
For no good reason there are error messages displayed after a while on the dashboard screen upper message diplay erea:

![wazicloud_error500_fetching_device_permissions](https://user-images.githubusercontent.com/62630067/108229368-0921fc80-7140-11eb-96de-a4d20b7460e0.gif)

**Comment by cdupont** [comment]
A big memory problem was resolved recently on the Amazon instance, could you retry?

**Comment by cdupont** [comment]
Closing, please reopen if the problem persists.
