### ISSUE TITLE
Gateway position update with wrong zoom factor

### ISSUE THREAD

**Issue by SvenZeisberg** [Waziup/WaziCloud#241]
If trying to adjust position of a gateway with mouse movement, and then zoom in for finer positioning, the zoom always jumps back to full zoom out. Therefore a manual exact positioning of the gateway position with mouse movements is NOT possible.
![waziup_wrong_position_zoom](https://user-images.githubusercontent.com/62630067/108232410-08d73080-7143-11eb-9e8d-b7605b09d224.gif)

**Comment by 24inch** [comment]
The described error does occurs on current version of dashboard. But you cannot set a position via map, you can only set it via the "GET YOUR LOCATION" button or via manual set of coordinates.

**Comment by cdupont** [comment]
Closing as non reproduced
