### ISSUE TITLE
Login window delivers wrong error message.

### ISSUE THREAD

**Issue by SvenZeisberg** [Waziup/WaziCloud#242]
The login process was only short typing and klicking (so it was very short) ...in a tab, which was open for some days. The the error message seems wrongly to refer to the open time of the tab in the browser and not, as claimed, to the login process?!

![image](https://user-images.githubusercontent.com/62630067/109240087-1e99c500-77d7-11eb-984a-78c53a316473.png)

**Comment by j-forster** [comment]
This window and the message is generated and managed by [KeyCloak](https://github.com/keycloak/keycloak).

If the tab was open for days the message looks good to me. `You took too long to login.` is true, no? It didn't say that the Login Process took too long - so the message is not wrong. Do you agree?

This issue will be closed as it is not in the scope of Waziup directly, but part of the KeyCloak interface - and modifying/forking the KeyCload interfaces is too much work for a single error message. You can create an issue for [KeyCloak](https://github.com/keycloak/keycloak) directly if you think the error message can be improved or should be more specific.

**Comment by cdupont** [comment]
Yeah it's a message from Keycloak, I've noticed it too. They have strict policies for login... Anyway you can re-click again on "Login" and it should go through.
