### ISSUE TITLE
The sensor values' chart is not shown in full size

### ISSUE THREAD

**Issue by mojtaba-esk** [Waziup/WaziCloud#247]
The sensor values' chart is not shown in full size
![image](https://user-images.githubusercontent.com/13765532/110664908-2474aa80-81c8-11eb-9580-fe5ae298faa2.png)

![image](https://user-images.githubusercontent.com/13765532/110664970-33f3f380-81c8-11eb-9c5c-f128d092a25b.png)

**Comment by j-forster** [comment]
Duplicate: https://github.com/Waziup/WaziCloud/issues/237
