### ISSUE TITLE
Notifications are not shown

### ISSUE THREAD

**Issue by mojtaba-esk** [Waziup/WaziCloud#253]
Probably it is fixed in the new version.

![image](https://user-images.githubusercontent.com/13765532/110667089-322b2f80-81ca-11eb-821d-e1b88e2fd03f.png)

When Click nothing shown:

![image](https://user-images.githubusercontent.com/13765532/110667031-23447d00-81ca-11eb-82ec-8c22923f0b9c.png)

For another one worked though. No idea why:

![image](https://user-images.githubusercontent.com/13765532/110667658-c3020b00-81ca-11eb-9531-b6da27a8685f.png)

**Comment by cdupont** [comment]
The first is an "actuation action" notification... So it's not showing on the production UI. :\

**Comment by cdupont** [comment]
Maybe I should publish the new dashboard as soon as possible and not care about updating the old one?

**Comment by mojtaba-esk** [comment]
Hopefully after update it will work, as I remember in your dev version it was working.

**Comment by cdupont** [comment]
This should be fixed, closing.
