### ISSUE TITLE
Empty window shown when switching from  Social to Actuation in the Notification configuration window

### ISSUE THREAD

**Issue by SvenZeisberg** [Waziup/WaziCloud#254]
Following the stage link to access the Cloud I get a "blue screen", if I want to shift the button from "Social" to "Actuation ...
![image](https://user-images.githubusercontent.com/62630067/110797373-4d08ad00-8279-11eb-8082-5d47435096d4.png)

![image](https://user-images.githubusercontent.com/62630067/110797433-5d208c80-8279-11eb-9a51-ca6942995a2e.png)

**Comment by cdupont** [comment]
Thanks, fixed!
